# Generated by Django 2.0.7 on 2018-07-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20180729_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='user',
        ),
    ]
