# Generated by Django 2.0.7 on 2018-07-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20180729_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='User',
        ),
    ]
