# Generated by Django 2.0.7 on 2018-07-29 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20180729_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
