# Generated by Django 2.0.7 on 2018-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20180729_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
